trigger: none

resources:
  repositories:
    - repository: foundation
      type: git
      name: YourCommonTemplateTeamProject/YourRepo

extends:
  template: ado-pipelines-template/model/Model.Infrastructure.PR.yml@foundation
  parameters:
    technology: Terraform
    environment: Development
    technologyParameters:
      working_directory: Infrastructure/Aks
      var_file: vars/development.tfvars
      service_connection: conn-azure-rg-devops-demo-dev
      location: westeurope
      backend_service_connection: conn-azure-rg-devops
      backend_storage_account: saterraforminfra
      backend_resource_group: rg-devops
      backend_container: tfstate
      state_key: aks-infrastructure-stg.tfstate
      command_arguments: '-var "location=westeurope"'