apiVersion: v1
kind: Service
metadata:
  name: demowebapp-service
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "false"
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.webAppService.port }}
      targetPort: {{ .Values.webAppService.targetPort }}
  selector:
    app: demowebapp